// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVJ_7YrQ7k4XLwpwFVfTnCcDpE8fxTPbM',
    appId: '1:547406038068:android:bcc234a9f183588ec37661',
    messagingSenderId: '547406038068',
    projectId: 'mayapur-bace',
    storageBucket: 'mayapur-bace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA37wmAvkE4Qv4QyFre_VL__kGXalm7sZg',
    appId: '1:547406038068:ios:924430a8a364c90cc37661',
    messagingSenderId: '547406038068',
    projectId: 'mayapur-bace',
    storageBucket: 'mayapur-bace.appspot.com',
    iosBundleId: 'com.example.mayapurBace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA37wmAvkE4Qv4QyFre_VL__kGXalm7sZg',
    appId: '1:547406038068:ios:924430a8a364c90cc37661',
    messagingSenderId: '547406038068',
    projectId: 'mayapur-bace',
    storageBucket: 'mayapur-bace.appspot.com',
    iosBundleId: 'com.example.mayapurBace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHxXfrmJo2wjbtbn5P5DxTTCP818p-eZY',
    appId: '1:547406038068:web:3cce63986015a15fc37661',
    messagingSenderId: '547406038068',
    projectId: 'mayapur-bace',
    authDomain: 'mayapur-bace.firebaseapp.com',
    storageBucket: 'mayapur-bace.appspot.com',
    measurementId: 'G-47QHG2JTXG',
  );
}
